### ISSUE TITLE
Information message is not showed in console

### ISSUE THREAD

**Issue by cocana** [claudiospizzi/ScriptLogger#5]
With powershell 5 information message is not showed in console.
change line 97 of Write-Log.ps1 (add -InformationAction Continue)

_'Information' { try { Write-Information -MessageData $Message -InformationAction Continue } catch { Write-Host $Message } }_

Also to avoid exception message with write-errorlog change line 99
_'Error'       { $Host.UI.WriteErrorLine("ERROR: $ErrorRecord")}_

**Comment by claudiospizzi** [comment]
Thanks for your input. You are right, the information message was not shown if the `$Global:InformationPreference` was set to `SilentlyContinue`. By the way, this applies to all levels. I've fixed it here: 2aba6b4

The exception message is written on purpose. With this way, you are able to see the _stack trace_ and even more important, on which file/script and line the error happens. With your solution, just the error message itself will be displayed. That's sometime not enough. Or do you have other drawbacks by using `Write-Error`?

**Comment by cocana** [comment]
It could be a little confusing if only want a error message, because in exception message shows like if the error would be on the module:

```
Write-Log : My Error Message
At C:\Program Files\WindowsPowerShell\Modules\ScriptLogger\1.1.1\Functions\Write-ErrorLog.ps1:34 char:13
+             Write-Log -Message $Message -Level 'Error'
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], Exception
    + FullyQualifiedErrorId : Unknown,Write-Log
```

I guess it would be better if only shows exception message if it is an system error and not a user message error.

Thanks

**Comment by claudiospizzi** [comment]
Good point! I've now added an additional change (https://github.com/claudiospizzi/ScriptLogger/commit/5039be59d4e941a04da134a0f7c179d07ec25c08). Here is the behavior:

``` powershell
PS C:\> Write-ErrorLog -Message 'My Error Message'
ERROR: My Error Message

PS C:\> try { 0/0 } catch { Write-ErrorLog -ErrorRecord $_ }
ERROR: Attempted to divide by zero. (C:\Temp\test.ps1:6 char:7)
```

Should now make more sense and if an ErrorRecord is provided, the invocation info will be logged too.
