### ISSUE TITLE
Add -Function parameter to Write-Log function

### ISSUE THREAD

**Issue by MiroslavMikus** [claudiospizzi/ScriptLogger#8]
Hi, would it be able to add -Function parameter to Write-Log function and therefore to all logging functions as well? 

So if you set up the $Global:ScriptLogger to 
```
Start-ScriptLogger -Path 'C:\Temp\test.log' ...
```
and than use for example 
```
Write-InformationLog -Message "Foo" -Function "Test"
```
the output will go to the 'C:\Temp\Test.log'. 

> Some idea for parameter for the Write-Log function
> ```
> Param(
> [Parameter(Mandatory = $false)]
> [string] $Function= $Global:ScriptLogger.Path
> )
> ```

**Comment by MiroslavMikus** [comment]
Another way to achieve the same result could be:
1. Make `Create-ScriptLogger` method. Same as `Set-ScriptLogger` just return the setup object back to the caller.
2. Make Write-log function accept the setup object directly.

So I could manage my own logger setups...

**Comment by claudiospizzi** [comment]
Hi @MiroslavMikus 

I think your goal ist to use multiple loggers the same time, right? What do you think about adding a name to a logger.

```powershell
Start-ScriptLogger -LoggerName 'FuncA' -Path C:\Temp\funcA.log
Start-ScriptLogger -LoggerName 'FuncB' -Path C:\Temp\funcB.log
```

And then for the write log functions, we can specify the logger name.

```powershell
Write-ErrorLog -LoggerName 'FuncA' -Path C:\Temp\funcA.log
```

The name is optional, we would use the default logger name "Default".

**Comment by claudiospizzi** [comment]
Hi @MiroslavMikus 

I've released a new version 3 of the module. With this version, multiple logger instances are now possible:

```
Start-ScriptLogger -Name 'Logger1' -Path 'C:\Temp\log1.log'
Start-ScriptLogger -Name 'Logger1' -Path 'C:\Temp\log2.log'

Write-InformationLog -Name 'Logger1' -Message 'Demo 1'
Write-InformationLog -Name 'Logger2' -Message 'Demo 2'
```

Regards
Claudio
